apiVersion: v1  # Specifies the API version
kind: PersistentVolume  # Specifies that this is a PersistentVolume resource
metadata:
  name: hostpath-pv  # Name of the persistent volume
  labels:
    type: local  # Label to identify the type of volume
spec:
  capacity:
    storage: 1Gi  # Storage capacity of the volume
  accessModes:
    - ReadWriteOnce  # Access mode for the volume
  hostPath:
    path: "/mnt/data"  # Path on the host where the volume is stored
