apiVersion: apps/v1  # Specifies the API version
kind: Deployment  # Specifies that this is a Deployment resource
metadata:
  name: dockerproj-deployment  # Name of the deployment
  namespace: dockerproj-nspace  # Namespace where the deployment is created
spec:
  replicas: 3  # Number of pod replicas to run
  selector:
    matchLabels:
      app: dockerproj  # Label selector to identify pods managed by this deployment
  template:
    metadata:
      labels:
        app: dockerproj  # Label to identify pods created by this deployment
    spec:
      containers:
      - name: dockerproj  # Name of the container
        image: ezelllow/dockerproj:latest  # Docker image to use for the container
        ports:
        - containerPort: 5001  # Port that the container listens on
        volumeMounts:
        - name: log-volume  # Name of the volume to mount
          mountPath: /mnt/log  # Path inside the container where the volume is mounted
      volumes:
      - name: log-volume  # Name of the volume, matching the name in volumeMounts
        persistentVolumeClaim:
          claimName: hostpath-pvc  # Name of the PVC to use for this volume
