apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerproj-deployment
  namespace: dockerproj-nspace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dockerproj
  template:
    metadata:
      labels:
        app: dockerproj
    spec:
      containers:
      - name: dockerproj
        image: ezelllow/dockerproj:latest
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: log-volume
          mountPath: /mnt/log
      volumes:
      - name: log-volume
        persistentVolumeClaim:
          claimName: hostpath-pvc

